### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Grassplate** [0PandaDEV/Nextron#102]
### Describe the bug

**I see this error when trying to run any command as a non-op.** 
_Server: Purpur_ _Client: NeoForge_

```

> [22:50:40 INFO]: JavaBlossom issued server command: /nextron:vanish
> [22:50:40 WARN]: java.lang.NullPointerException
> [22:50:40 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
> [22:50:40 WARN]:        at java.base/java.util.Optional.of(Optional.java:113)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.message.MessageRegistry.get(MessageRegistry.java:47)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.message.MessageRegistry.getInvoked(MessageRegistry.java:35)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.permission.MissingPermissionResultHandler.handle(MissingPermissionResultHandler.java:20)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.permission.MissingPermissionResultHandler.handle(MissingPermissionResultHandler.java:10)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.handler.result.ResultHandleServiceImpl.resolve(ResultHandleServiceImpl.java:40)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.handler.result.ResultHandleServiceImpl.resolve(ResultHandleServiceImpl.java:24)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.command.executor.CommandExecuteService.handleResult(CommandExecuteService.java:85)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$1(CommandExecuteService.java:65)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.tryRun(BukkitSchedulerImpl.java:74)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplySync(BukkitSchedulerImpl.java:46)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplyLater(BukkitSchedulerImpl.java:28)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.scheduler.Scheduler.supply(Scheduler.java:52)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$2(CommandExecuteService.java:64)
> [22:50:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
> [22:50:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:64)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.command.CommandManager$PlatformListener.execute(CommandManager.java:63)
> [22:50:40 WARN]:        at Nextron-1.6.0.jar//dev.rollczi.litecommands.bukkit.BukkitCommand.execute(BukkitCommand.java:50)
> [22:50:40 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
> [22:50:40 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> [22:50:40 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
> [22:50:40 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
> [22:50:40 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> [22:50:40 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> [22:50:40 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> [22:50:40 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)
> [22:50:40 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:358)
> [22:50:40 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:345)
> [22:50:40 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:340)
> [22:50:40 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297)
> [22:50:40 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271)
> [22:50:40 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [22:50:40 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
> [22:50:40 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
> [22:50:40 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544)
> [22:50:40 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355)
> [22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
> [22:50:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Steps to reproduce

1. Create Purpur server (version 2304) 
2. Add latest version of Nextron
3. Run any command

### Expected behavior

I expected a simple message saying "You do not have permission"

### Version of Nextron

1.6.0

### Additional context

This error only appears when the user is not-op but I expect it shouldn't give an error code.

**Comment by Grassplate** [comment]
I've decided to close this bug since I assume it's already fix
