### ISSUE TITLE
[feature request] World manager

### ISSUE THREAD

**Issue by TOWUK** [0PandaDEV/Nextron#7]
mw to world
and load unload
and more like a multiworld / multiverse core
please do it! <3
u are best!

**Comment by TOWUK** [comment]
and fix it:
[00:13:42 INFO]: TOWUK issued server command: /help nextron
[00:13:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'help' in plugin Nextron v1.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-129]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-129]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2342) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2302) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-129]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-129]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "localCommandInfo" is null
        at tk.pandadev.nextron.commands.CommandBase.getUsage(CommandBase.java:63) ~[Nextron-1.4.3.jar:?]
        at tk.pandadev.nextron.commands.HelpCommand.execute(HelpCommand.java:52) ~[Nextron-1.4.3.jar:?]
        at tk.pandadev.nextron.commands.CommandBase.onCommand(CommandBase.java:48) ~[Nextron-1.4.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
>
>

**Comment by 0PandaDEV** [comment]
Thanks for the feedback the help command is used like this `/help <commandName>` 

I will look over the world manager and maybe integrate multiverse core into Nextron in the future.

**Comment by 0PandaDEV** [comment]
Is implemented in the newest commit https://github.com/0PandaDEV/Nextron/commit/b8a6771a88f6d31793e137e6891642682c858abd and https://github.com/0PandaDEV/Nextron/commit/561bf1c15ae57c27675fe8463b0525df0c600fde and https://github.com/0PandaDEV/Nextron/commit/3b119c6ca0caacafad0a2f43bfd2d47bb915be29, will be released in 1.5.0 soon.
